package com.lgq.rssreader.share;

public class ShareEventArgs<T> {
    /// <summary>
    /// Result of request
    /// </summary>
    public Boolean Result;

    /// <summary>
    /// data you request
    /// </summary>
    public T Data;

    /// <summary>
    /// Gets a value that indicates which error occurred during an asynchronous operation.
    /// </summary>
    public Exception Error;

    /// <summary>
    /// Creates a new instance of DownloadStringCompletedEventArgs with the specified result data.
    /// </summary>
    /// <param name="result">The data that is downloaded by a DownloadStringAsync method.</param>
    public ShareEventArgs(Boolean result, T data)
    {
        Data = data;
        Result = result;
    }

    /// <summary>
    /// Creates a new instance of DownloadStringCompletedEventArgs with the specified exception.
    /// </summary>
    /// <param name="ex">The exception generated by the asynchronous operation.</param>
    public ShareEventArgs(Exception ex)
    {
        Error = ex;
    }
}
